# Generated by Django 4.1.4 on 2022-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation_decharge', models.CharField(default='', max_length=100)),
                ('description_decharge', models.CharField(default='', max_length=100)),
                ('dimension_decharge', models.CharField(default='', max_length=100)),
                ('dechets_observes', models.CharField(default='', max_length=100)),
                ('nuisances_observees', models.CharField(default='', max_length=100)),
                ('description_situation', models.CharField(default='', max_length=100)),
                ('observation', models.CharField(default='', max_length=100)),
                ('photo_decharge', models.ImageField(upload_to='pictures')),
                ('geolocalisation_longitude', models.CharField(default='', max_length=100)),
                ('geolocalisation_latitude', models.CharField(default='', max_length=100)),
                ('geolocalisation_altitude', models.CharField(default='', max_length=100)),
                ('geolocalisation_altitudeAccuracy', models.CharField(default='', max_length=100)),
                ('geolocalisation_accuracy', models.CharField(default='', max_length=100)),
                ('geolocalisation_speed', models.CharField(default='', max_length=100)),
                ('timestamp', models.CharField(default='', max_length=100)),
                ('data_operation', models.CharField(default='', max_length=50)),
                ('date_heure_operation', models.CharField(default='', max_length=50)),
                ('month_year_operation', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
