# Generated by Django 4.1.4 on 2023-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukafuluapi', '0002_alter_decharges_photo_decharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decharges',
            name='photo_decharge',
            field=models.FileField(upload_to='pictures'),
        ),
    ]
