# Generated by Django 4.1.4 on 2023-05-12 04:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lukafuluapi', '0003_alter_decharges_photo_decharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decharges',
            name='photo_decharge',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
